parameters:
  host: "wss://bsc.getblock.io/testnet/?api_key=b97342bc-55a6-442e-b015-ff12e0a76356" # Address of node, WSS or IPC
  privatekey: "120a44a051725e36d2b0f656e44b72505b461a2de8a0da3a276d1c0b6994bd7a" # Private key of wallet to buy with
  amountin: 0.001 # Amount to buy with
  presaleaddress: "0xd8586C82F0851D8736e427AFAD64650a29881764" # Address of the presale, not token address!
  percentfill: 51 # When the presale is this full, buy. Tune to your liking
  action: "pinksale" # pinksale, dxSale, unicrypt